# Generated by Django 5.0 on 2024-02-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0012_invoice_cgst_invoice_sgst_invoice_upi_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_GSTnumber',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_GSTtype',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_billingaddress',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_place_of_supply',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
