# Generated by Django 5.0 on 2024-03-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0016_attendance_attendance_comment_attendance_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Company_Staff.pricelist'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price_list_applied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
